// flow-typed signature: 4bb0fa99a5fa54b4e1f31fe32cd03ec3
// flow-typed version: <<STUB>>/dlv_v^1.1.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dlv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dlv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dlv/dist/dlv.es' {
  declare module.exports: any;
}

declare module 'dlv/dist/dlv' {
  declare module.exports: any;
}

declare module 'dlv/dist/dlv.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dlv/dist/dlv.es.js' {
  declare module.exports: $Exports<'dlv/dist/dlv.es'>;
}
declare module 'dlv/dist/dlv.js' {
  declare module.exports: $Exports<'dlv/dist/dlv'>;
}
declare module 'dlv/dist/dlv.umd.js' {
  declare module.exports: $Exports<'dlv/dist/dlv.umd'>;
}
declare module 'dlv/index' {
  declare module.exports: $Exports<'dlv'>;
}
declare module 'dlv/index.js' {
  declare module.exports: $Exports<'dlv'>;
}
